# Generated by Django 6.0 on 2025-12-17 03:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('user_id', models.CharField(max_length=255)),
                ('purchase_date', models.DateTimeField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_url', models.URLField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField(default=1)),
                ('category', models.CharField(choices=[('groceries', 'Groceries'), ('beverages', 'Beverages'), ('dairy', 'Dairy'), ('produce', 'Produce'), ('meat', 'Meat & Protein'), ('bakery', 'Bakery'), ('frozen', 'Frozen Foods'), ('pantry', 'Pantry Staples'), ('snacks', 'Snacks'), ('medication', 'Medication'), ('health', 'Health & Wellness'), ('personal_care', 'Personal Care'), ('toiletries', 'Toiletries'), ('household', 'Household Supplies'), ('cleaning', 'Cleaning Products'), ('paper_products', 'Paper Products'), ('pet_supplies', 'Pet Supplies'), ('baby_products', 'Baby Products'), ('electronics', 'Electronics'), ('restaurant', 'Restaurant'), ('clothing', 'Clothing'), ('school_supplies', 'School Supplies'), ('transportation', 'Transportation'), ('entertainment', 'Entertainment'), ('utilities', 'Utilities'), ('gas', 'Gas'), ('taxes', 'Taxes'), ('other', 'Other')], default='other', max_length=20)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='receipt.receipt')),
            ],
        ),
    ]
