# Generated by Django 6.0 on 2026-06-17 12:42

import pgvector.django.vector
from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0002_receipt_extracted_text_receipt_extraction_result'),
    ]

    operations = [
        VectorExtension(),
        migrations.AddField(
            model_name='receiptitem',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
    ]
