# Generated by Django 6.0 on 2026-07-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0003_receiptitem_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptitem',
            name='category',
            field=models.CharField(choices=[('groceries', 'Groceries'), ('beverages', 'Beverages'), ('alcohol', 'Alcohol'), ('dairy', 'Dairy'), ('fruits', 'Fruits'), ('vegetables', 'Vegetables'), ('produce', 'Produce'), ('meat', 'Meat & Protein'), ('bakery', 'Bakery'), ('frozen', 'Frozen Foods'), ('pantry', 'Pantry Staples'), ('snacks', 'Snacks'), ('medication', 'Medication'), ('health', 'Health & Wellness'), ('personal_care', 'Personal Care'), ('toiletries', 'Toiletries'), ('household', 'Household Supplies'), ('cleaning', 'Cleaning Products'), ('paper_products', 'Paper Products'), ('pet_supplies', 'Pet Supplies'), ('baby_products', 'Baby Products'), ('electronics', 'Electronics'), ('restaurant', 'Restaurant'), ('clothing', 'Clothing'), ('school_supplies', 'School Supplies'), ('transportation', 'Transportation'), ('entertainment', 'Entertainment'), ('utilities', 'Utilities'), ('gas', 'Gas'), ('taxes', 'Taxes'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
