# Generated by Codex on 2026-07-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0005_receipt_discount_amount_receipt_store_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.UniqueConstraint(
                condition=models.Q(file_hash__isnull=False),
                fields=('user_id', 'file_hash'),
                name='unique_receipt_file_hash_per_user',
            ),
        ),
    ]
