# Generated by Codex on 2026-07-17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0006_receipt_file_hash_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('processing', 'Processing'),
                    ('needs_review', 'Needs review'),
                    ('completed', 'Completed'),
                    ('failed', 'Failed'),
                ],
                default='pending',
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name='ReceiptExtractionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('needs_review', 'Needs review'), ('approved', 'Approved')], default='needs_review', max_length=20)),
                ('overall_confidence', models.FloatField(default=0.0)),
                ('issues', models.JSONField(blank=True, default=list)),
                ('raw_extraction', models.JSONField(blank=True, default=dict)),
                ('corrected_payload', models.JSONField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=255, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_review', to='receipt.receipt')),
            ],
        ),
    ]
