# Generated by Django 6.0 on 2026-07-17 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0007_receipt_extraction_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptitem',
            name='category',
            field=models.CharField(choices=[('groceries', 'Abarrotes'), ('beverages', 'Bebidas'), ('alcohol', 'Bebidas Alcohólicas'), ('dairy', 'Lácteos'), ('fruits', 'Frutas'), ('vegetables', 'Verduras'), ('produce', 'Productos Frescos'), ('meat', 'Carnes y Proteínas'), ('bakery', 'Panadería'), ('frozen', 'Productos Congelados'), ('pantry', 'Despensa'), ('snacks', 'Botanas'), ('medication', 'Medicamentos'), ('health', 'Salud y Bienestar'), ('personal_care', 'Cuidado Personal'), ('toiletries', 'Artículos de Tocador'), ('household', 'Suministros del Hogar'), ('cleaning', 'Productos de Limpieza'), ('paper_products', 'Productos de Papel'), ('pet_supplies', 'Suministros para Mascotas'), ('baby_products', 'Productos para Bebés'), ('electronics', 'Electrónica'), ('restaurant', 'Restaurante'), ('clothing', 'Ropa'), ('school_supplies', 'Útiles Escolares'), ('transportation', 'Transporte'), ('entertainment', 'Entretenimiento'), ('utilities', 'Servicios'), ('gas', 'Gasolina'), ('taxes', 'Impuestos'), ('other', 'Otro')], default='other', max_length=20),
        ),
    ]
