# Generated by Django 6.0 on 2026-07-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0008_alter_receiptitem_category'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='receiptextractionreview',
            index=models.Index(fields=['status', '-updated_at'], name='receipt_review_queue_idx'),
        ),
    ]
