# Generated by Codex on 2026-07-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0009_receiptextractionreview_receipt_review_queue_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='source_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='receipt',
            name='source_type',
            field=models.CharField(
                choices=[
                    ('unknown', 'Unknown'),
                    ('telegram', 'Telegram'),
                    ('manual_upload', 'Manual upload'),
                ],
                default='unknown',
                max_length=32,
            ),
        ),
    ]
