# Generated by Codex on 2026-07-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipt", "0012_receiptitem_unit_price_line_total"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="receipt",
            name="unique_receipt_file_hash_per_user",
        ),
        migrations.AddField(
            model_name="receipt",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddConstraint(
            model_name="receipt",
            constraint=models.UniqueConstraint(
                condition=models.Q(file_hash__isnull=False, is_active=True),
                fields=("user_id", "file_hash"),
                name="unique_active_receipt_file_hash_per_user",
            ),
        ),
    ]
