# Generated by Codex on 2026-07-25

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipt", "0013_receipt_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receiptitem",
            name="quantity",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("1.000"),
                max_digits=10,
            ),
        ),
    ]
