# Generated by Django 6.0 on 2026-08-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0014_receiptitem_decimal_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
